# Site settings
title: zainras
description: My Code My Adventure
cover: assets/images/home.jpeg
logo: assets/images/logo.png
favicon: assets/images/favicon.ico
baseurl: "/" # the subpath of your site, e.g. /blog/ or / for root
url: "https://zainras.github.io" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

# Social
facebook: mochamad.rasyid
twitter: zain_ras
github:  zainras

#Additional Pages
about: about
contact: contact
privacy-policy: privacy-policy


permalink: /:title


# Google Analytics
analytics_id: "UA-81008608-3"

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate


# Settings for rake task
safe: False
lsi: False
username: zainras #github username
repo: zainras.github.io #github repository
branch: master #branch
relative_source: ../hanuman/ #source directory
destination: ../hanuman-pages/ #destination directory
production_url:  https://zainras.github.io/
source_url:  https://github.com/zainras/zainras.github.io #source repository url

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
